ARG BASETEST=centos:7

#
# builder
#
FROM alpine:edge AS figlet-builder

RUN apk update && apk add --no-cache gcc musl-dev make curl unzip findutils fdupes

WORKDIR /build

# figlet
RUN curl -skL -o figlet-master.zip https://github.com/cmatsuoka/figlet/archive/refs/heads/master.zip && \
    unzip -q -o figlet-master.zip && \
    cd figlet-master && \
    make LDFLAGS=-static -j install && \
    strip -s /usr/local/bin/figlet && \
    rm /usr/local/bin/chkfont /usr/local/bin/showfigfonts

# lolcat-c
RUN curl -skL https://raw.githubusercontent.com/jaseg/lolcat/main/lolcat.c | \
    cc -o /usr/local/bin/lolcat -static -std=c99 -x c - -lm && \
    strip -s /usr/local/bin/lolcat

# toilet
RUN apk add pkgconfig g++ zlib-dev zlib-static

RUN curl -skL https://github.com/cacalabs/libcaca/releases/download/v0.99.beta20/libcaca-0.99.beta20.tar.gz | tar -xz && \
    cd libcaca-0.99.beta20 && \
    ./configure --enable-static --disable-shared --disable-cxx && \
    cd caca && \
    make -j install && \
    # fix zlib imports when statically linking
    sed -i 's/^\(Libs:.*\)/\1 -lz/;s/^\(Libs.private:\).*$/\1/' /usr/local/lib/pkgconfig/caca.pc

RUN curl -skL http://caca.zoy.org/raw-attachment/wiki/toilet/toilet-0.3.tar.gz | tar -xz && \
    cd toilet-0.3 && \
    ./configure --prefix=/usr/local && \
    make LDFLAGS=-static -j install && \
    strip -s /usr/local/bin/toilet

# fonts
RUN curl -skL -o figlet-fonts-master.zip https://github.com/xero/figlet-fonts/archive/refs/heads/master.zip && \
    unzip -q -o -d /usr/local/share/figlet/ -j figlet-fonts-master.zip && \
    # curl -skL -o figlet-fonts-master2.zip https://github.com/cmatsuoka/figlet-fonts/archive/refs/heads/master.zip && \
    # unzip -q -o -d /usr/local/share/figlet/ -j figlet-fonts-master2.zip '*.tlf' '*.flf' && \
    chmod 644 /usr/local/share/figlet/* && \
    fdupes -i -N -q -d /usr/local/share/figlet

# show fonts
RUN (echo '#!/bin/sh' ;\
    echo 'find --version 2>&1 | grep -q GNU || { echo "GNU find required"; exit 1; }' ;\
    echo 'find /usr/local/share/figlet/ -name "*.?lf" -printf "%P\n" | sort | while read a; do a=$(basename "$a" .flf); a=$(basename "$a" .tlf); echo; echo "$a :"; figlet -w120 -f "$a" "${1:-$a}"; done') > /usr/local/bin/figlet-fonts && \
    chmod 755 /usr/local/bin/figlet-fonts


# sl
RUN apk add --no-cache ncurses-dev ncurses-static
RUN curl -skL -o sl-master.zip https://github.com/mtoyoda/sl/archive/refs/heads/master.zip && \
    unzip -qo sl-master.zip && \
    cd sl-master && \
    cc -O2 -o sl sl.c -lncursesw -static && \
    install -s sl /usr/local/bin/sl

#
# tests
#
FROM ${BASETEST} AS test

ARG RANDOM 0
COPY --from=figlet-builder --chown=0:0 /usr/local/share/figlet /some/where//share/figlet
COPY --from=figlet-builder --chown=0:0 /usr/local/bin /some/where/bin
ENV PATH=/some/where/bin:$PATH
ENV FIGLET_FONTDIR=/some/where/share/figlet
RUN figlet -f mini Hello | lolcat -f -r | sed 's/^/@\ /' ; echo
RUN toilet -d /some/where/share/figlet --metal -f small World | sed 's/^/@\ /' ; echo

#
# dist image
#
FROM scratch AS figlet

COPY --from=figlet-builder --chown=0:0 /usr/local/share/figlet /share/figlet
COPY --from=figlet-builder --chown=0:0 /usr/local/bin /
